In [47]:
import numpy as np

X = np.array([10, 2, 5, 1]) 

K = np.array([[800, 0, 0],
              [0, 800, 0],
              [0,   0, 1]])

print("Coordinates of the 3D point:\n", X)
print("Intrinsic matrix of the camera:\n", K)

Coordinates of the 3D point:
 [10  2  5  1]
Intrinsic matrix of the camera:
 [[800   0   0]
 [  0 800   0]
 [  0   0   1]]


In [48]:
R1 = np.eye(3)
t1 = np.zeros((3,1))
P1 = K @ np.hstack((R1, t1))

R2 = np.eye(3)
t2 = np.array([[1],[-3],[0]])
P2 = K @ np.hstack((R2, -t2))

print("Projection matrix for camera 1:\n", P1)
print("Projection matrix for camera 2:\n", P2)

Projection matrix for camera 1:
 [[800.   0.   0.   0.]
 [  0. 800.   0.   0.]
 [  0.   0.   1.   0.]]
Projection matrix for camera 2:
 [[ 8.0e+02  0.0e+00  0.0e+00 -8.0e+02]
 [ 0.0e+00  8.0e+02  0.0e+00  2.4e+03]
 [ 0.0e+00  0.0e+00  1.0e+00  0.0e+00]]


In [49]:
def project(P, X):
    x = P @ X
    return x[:2] / x[2]

In [50]:
x1 = project(P1, X) 
x2 = project(P2, X)
print("Pixel in Cam1:", x1)
print("Pixel in Cam2:", x2)

Pixel in Cam1: [1600.  320.]
Pixel in Cam2: [1440.  800.]


In [51]:
def hat(v): 
    return np.array([[0, -v[2], v[1]],
                     [v[2], 0, -v[0]],
                     [-v[1], v[0], 0]])

In [52]:
R = R2 @ R1.T
t = t2
E = hat(t.flatten()) @ R
print("Essential matrix:\n", E)

Essential matrix:
 [[ 0.  0. -3.]
 [ 0.  0. -1.]
 [ 3.  1.  0.]]


In [53]:
p1 = np.array([x1[0], x1[1], 1])
l2 = E @ p1
print("Epipolar line in Cam2:", l2)

p2 = np.array([x2[0], x2[1], 1])
val = p2 @ l2
print("Check p2 lies on line:", val)

Epipolar line in Cam2: [-3.00e+00 -1.00e+00  5.12e+03]
Check p2 lies on line: 0.0
